### ISSUE TITLE
Add module pve_role

### ISSUE THREAD

**Issue by trickert76** [lae/ansible-role-proxmox#109]
Today I want add a Icinga check (check_pve https://github.com/nbuchwitz/check_pve) and that check needs a user with specifc roles that are not matching the buildin roles and so I needed to add a new role manually...wtf.

So - I'll create a module pve_role that is similar to the existing pve_acl role. It's not that important but it would "round up" the role.

The role will have the following attributes

    pve_role:
      name: "monitoring"
      privileges:
        - "Sys.Modify"
        - "Sys.Audit"
        - "Datastore.Audit"
        - "VM.Monitor"
        - "VM.Audit"

**Comment by trickert76** [comment]
I've created a feature branch and will test that now

**Comment by lae** [comment]
Closed via #112.
