### ISSUE TITLE
single node deployment in one inventory

### ISSUE THREAD

**Issue by penguin02007** [lae/ansible-role-proxmox#117]
Is it possible deploy a single/non-clustered nodes in one inventory file?

The role always assume clustering even `pve_cluster_enabled: no`,  ansible run with  `--limit` flag will result with the following unless I removed all hosts in the group.

```
failed: [node1] (item=node2) => {
    "ansible_loop_var": "item",
    "assertion": "hostvars[item].ansible_facts",
    "changed": false,
    "evaluated_to": false,
    "item": "node2",
    "msg": "Could not load facts for node2. Please run your playbook against all hosts in proxmox."
}
```

```
[proxmox]
node1 
node2  
...
```

**Comment by lae** [comment]
What are your role variables set to?

**Comment by penguin02007** [comment]
Most of the role variables are set in playbook or `group_vars`

```
$ cat group_vars/all
---
ntp_manage_config: true
ntp_servers:
  - 0.pool.ntp.org iburst
  - 1.pool.ntp.org iburst
  - 2.pool.ntp.org iburst
  - 3.pool.ntp.org iburst
RAQ10-642:proxmox-ansible ka.chan$ cat group_vars/pve01
---
pve_group: pve01
pve_fetch_directory: "fetch/{{ pve_group }}/"
pve_watchdog: ipmi
pve_ssl_private_key: "{{ lookup('file', pve_group + '/' + inventory_hostname + '.key') }}"
pve_ssl_certificate: "{{ lookup('file', pve_group + '/' + inventory_hostname + '.pem') }}"
pve_cluster_enabled: yes
pve_groups:
  - name: ops
    comment: Operations Team
pve_users:
  - name: admin1@pam
    email: admin1@lab.local
    firstname: Admin
    lastname: User 1
    groups: [ "ops" ]
  - name: admin2@pam
    email: admin2@lab.local
    firstname: Admin
    lastname: User 2
    groups: [ "ops" ]
pve_acls:
  - path: /
    roles: [ "Administrator" ]
    groups: [ "ops" ]
interfaces_template: "interfaces-{{ pve_group }}.j2"
pve_cluster_ring0_addr: "{{ cluster_ip }}"
pve_cluster_bindnet0_addr: "192.168.199.0"

$ tree
.
├── README.md
├── bos1.ini
├── examples
│   └── interfaces
├── group_vars
│   ├── all
│   └── pve01
├── host_vars
│   ├── node1.yml
│   └── node2.yml
├── install_proxmox.yml
├── roles
│   └── requirements.yml
├── setup_networking.yml
├── templates
│   └── interfaces.j2
├── use1.ini
└── usw1.ini
```

**Comment by lae** [comment]
In `~/.ansible/roles/lae.proxmox/tasks/main.yml` add the following condition to the first `assert` task (under the `with_items` line):

```
  when: "pve_cluster_enabled | bool"
```

I'll need to go through and consider whether there are any ramifications for this in usual deployments but I'm thinking not. It *might* get confusing if folks drop clustered hosts in the same group as non-clustered hosts, however...

**Comment by penguin02007** [comment]
Thanks!That fix it.

The use case for this would be adding a new standalone hosts or limit the install on one host. I would imgine something like this -

```
$cat host.ini
[proxmox]
node1
node2
node3
node4

[pve1]
node1
node2


cat group_vars/pve1.yml
---
pve_cluster_enabled: yes

$cat host_vars/node3.yml
---
pve_cluster_enabled: no
```

**Comment by lae** [comment]
Yes, however a mixed inventory like that makes things confusing. I think there should be a clear separation between clustered hosts and non-clustered hosts in a playbook, because this role does things significantly different for clustered hosts, and a mistake might cause the inclusion of a node in some cluster unintentionally.

A more preferable `inventory`/`hosts.ini` in my opinion:
```
[proxmox]
node3
node4

[proxmox_clusters:children]
pve1
pve2

[pve1]
node1
node2

[pve2]
node5
node6
```

**Comment by mape2k** [comment]
> In `~/.ansible/roles/lae.proxmox/tasks/main.yml` add the following condition to the first `assert` task (under the `with_items` line) and please report back if this resolves the issue for you:
> 
> ```
>   when: "pve_cluster_enabled | bool"
> ```

Thanks for this fix. We run in the same issue when provisioning single non-clustered nodes.

**Comment by lae** [comment]
@penguin02007 @mape2k 1.6.8 has this fix now. Feel free to upgrade to it.
