### ISSUE TITLE
Single Node Install

### ISSUE THREAD

**Issue by liambresnahan** [lae/ansible-role-proxmox#126]
Wondering if I could get some help. I'm trying get a single node install (no cluster) running and struggling. It mostly appears to be down to the /etc/hosts file not being set properly. Looking at the tasks around that it seems to only run when clustering. Additionally it seems to not set the IP address of the machine (per the proxmox on Debian guidance here - https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_Buster )

Am I missing something? Or should the step 'Enumerate all cluster hosts within the hosts file' actually run for each host no matter the clustering and also be broadened to include the servers IP address (instead of localhost/127.0.0.1)?

**Comment by lae** [comment]
Sounds like a possible bug.

Can you post the relevant output from the ansible play and role variables? Or if it runs successfully, please post the role variables and explain what errors/problem you're running into on the resulting server.

**Comment by liambresnahan** [comment]
this is the step that fails (and after editing /etc/hosts to the correct values will work):

`TASK [lae.proxmox : Install Proxmox VE and related packages] **************************************************************************
FAILED - RETRYING: Install Proxmox VE and related packages (2 retries left).
FAILED - RETRYING: Install Proxmox VE and related packages (1 retries left).
fatal: [blue.home.arpa]: FAILED! => {"attempts": 2, "cache_update_time": 1616813980, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'proxmox-ve'' failed: E: Sub-process /usr/bin/dpkg returned an error code (1)\n", "rc": 100, "stderr": "E: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stderr_lines": ["E: Sub-process /usr/bin/dpkg returned an error code (1)"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nproxmox-ve is already the newest version (6.3-1).\n0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.\n2 not fully installed or removed.\nAfter this operation, 0 B of additional disk space will be used.\nSetting up pve-manager (6.3-6) ...\r\nJob for pvestatd.service failed because the control process exited with error code.\r\nSee \"systemctl status pvestatd.service\" and \"journalctl -xe\" for details.\r\ndpkg: error processing package pve-manager (--configure):\r\n installed pve-manager package post-installation script subprocess returned error exit status 1\r\ndpkg: dependency problems prevent configuration of proxmox-ve:\r\n proxmox-ve depends on pve-manager; however:\r\n  Package pve-manager is not configured yet.\r\n\r\ndpkg: error processing package proxmox-ve (--configure):\r\n dependency problems - leaving unconfigured\r\nErrors were encountered while processing:\r\n pve-manager\r\n proxmox-ve\r\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "proxmox-ve is already the newest version (6.3-1).", "0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.", "2 not fully installed or removed.", "After this operation, 0 B of additional disk space will be used.", "Setting up pve-manager (6.3-6) ...", "Job for pvestatd.service failed because the control process exited with error code.", "See \"systemctl status pvestatd.service\" and \"journalctl -xe\" for details.", "dpkg: error processing package pve-manager (--configure):", " installed pve-manager package post-installation script subprocess returned error exit status 1", "dpkg: dependency problems prevent configuration of proxmox-ve:", " proxmox-ve depends on pve-manager; however:", "  Package pve-manager is not configured yet.", "", "dpkg: error processing package proxmox-ve (--configure):", " dependency problems - leaving unconfigured", "Errors were encountered while processing:", " pve-manager", " proxmox-ve"]}

PLAY RECAP ****************************************************************************************************************************
blue.home.arpa             : ok=13   changed=4    unreachable=0    failed=1    skipped=22   rescued=0    ignored=0   `

I also notice that in the single node configuration the step below that I would expect edits /etc/hosts is not run:

`TASK [lae.proxmox : Enumerate all cluster hosts within the hosts file] ****************************************************************
skipping: [blue.home.arpa]

TASK [lae.proxmox : Remove conflicting lines in hosts files] **************************************************************************
skipping: [blue.home.arpa]`

lastly, my role variables are set as such:
`ip_address: 192.168.50.201
hostname: blue
#lae.proxmox
pve_cluster_enabled: no
pve_group: pve01
pve_reboot_on_kernel_update: true
pve_zfs_enabled: yes`

**Comment by lae** [comment]
Sorry for the late reply - haven't really been on top of things lately.

> step that fails

It looks like there's an issue with the installed packages that's causing that task to fail:

```
Job for pvestatd.service failed because the control process exited with error code.
See "systemctl status pvestatd.service" and "journalctl -xe" for details.
```

If you can check that log and locate an error, it should help in figuring out where the issue lies. As far as I can tell, your role variables are fine and should work for a single node (but do make sure that NTP is set up, since that's necessary).

>  I would expect edits /etc/hosts is not run:

The task output you provided indicates that the tasks are skipped, which seems to be what you expected? Ansible will go through every single task but will tell you whether or not it actually executes (with "changed:"), but in this case it shows "skipping:". The hosts file isn't modified on single node deployments on the current release.

**Comment by jmariondev** [comment]
I just recently installed a single-host installation from scratch and ran into the same issue in the OP. Adding the machine's (non-localhost) IP to `/etc/hosts` is what remedied the issue.

Perhaps this task needs to be enabled for single-host installs too?

**Comment by lae** [comment]
Revisited a couple PRs/issues related to this. So, I just want to confirm, there needs to be a task that ensures that `x.x.x.x a.b.c` is in `/etc/hosts` where *a.b.c* is the `ansible_hostname` and x.x.x.x is the host IP address (and nothing to do with pvelocalhost, right?)?

It would need to be a separate task that runs exclusively for single nodes to support the use case of a "standalone pve host" inventory group (see https://github.com/lae/ansible-role-proxmox/issues/117#issuecomment-778352502).

**Comment by jmariondev** [comment]
Yes, that's what it sounds like according to the doc linked in the OP: https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_Buster#Add_an_.2Fetc.2Fhosts_entry_for_your_IP_address

**Comment by lae** [comment]
@liambresnahan can you confirm that the fix John submitted resolves this issue for you? You can obtain the development version via `ansible-galaxy` with the following:

```
ansible-galaxy install -f https://github.com/lae/ansible-role-proxmox/archive/develop.tar.gz,develop,lae.proxmox
```

**Comment by philippwaller** [comment]
@lea, there is still a minor problem with the hosts file. By default, this entry is created after the Debian installation:

`127.0.1.1	debian10-test-bench.yourdomain.com	debian10-test-bench`

However, this line need to be removed/replace in order to avoid the dpkg error message.

**Comment by lae** [comment]
@philippwaller I think this was an issue with the regular expression in the original PR not working correctly. This was fixed a couple weeks ago (https://github.com/lae/ansible-role-proxmox/commit/fbe315c57c0856e8048c35074efb6fb16d6bbb93). Can you try seeing if this resolved it for you?
