### ISSUE TITLE
ansible --check fails on clean controller

### ISSUE THREAD

**Issue by phemmer** [lae/ansible-role-proxmox#132]
When `ansible-playbook --check` is run on a new controller, the playbook fails with:
```
TASK [lae.proxmox : Authorize all hosts' root SSH public keys] *****************
[WARNING]: Unable to find '/runner/project/roles/proxmox/files/fetch/host1.example.com/root_rsa.pub' in expected paths (use -vvvvv to see paths)
fatal: [host1.example.com]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: /runner/project/roles/proxmox/files/fetch/host1.example.com/root_rsa.pub"}
[WARNING]: Unable to find '/runner/project/roles/proxmox/files/fetch/host1.example.com/root_rsa.pub' in expected paths (use -vvvvv to see paths)
fatal: [host2.example.com]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: /runner/project/roles/proxmox/files/fetch/host1.example.com/root_rsa.pub"}
```

In my case, I'm running AWX, and so the execution environment is clean with no state from previous runs. The previous task (`Fetch root SSH public key`) is skipped when running `--check`, and thus the `lookup('file',...)` in this task fails.

I can think of 2 solutions to the problem.  
One is to add `check_mode` to the fetch task so it runs, even in check mode. While this might violate the principle of `--check`, it's effectively operating as a cache, and will be corrected on the next non-`--check` run.  
The other option is to use `slurp` instead of `fetch`. This way it's only fetching into memory, and not affecting persistent state.

Edit:  
This was the first task that failed due to the issue. However reading further on in the play, there are other `fetch` tasks that will fail with the same scenario.

**Comment by lae** [comment]
`slurp` will only work for singular hosts as far as I recall? (without using delegation I guess) The keys need to be fetched for all hosts so that they can be accessed by every other host.

Is there another way to get around this while still keeping the public keys in playbook repos? The Ceph ansible role seems to use fetch as well, maybe they're doing that we could do here?
