### ISSUE TITLE
Kernel reboot in cluster mode

### ISSUE THREAD

**Issue by trickert76** [lae/ansible-role-proxmox#145]
When `pve_reboot_on_kernel_update` is `true` in cluster mode it would be better to throttle the reboot process to 1 to avoid any kind of cluster problem (out of sync). I would change the following code in kernel_updates.yml

    - name: "Reboot for kernel update"
      throttle: 1
      reboot:
        msg: "PVE kernel update detected by Ansible"
        pre_reboot_delay: "{{ pve_reboot_on_kernel_update_delay }}"
        post_reboot_delay: "{{ pve_reboot_on_kernel_update_delay }}"
      when:
        - "pve_reboot_on_kernel_update | bool"
        - "_pve_kernel_update.new_kernel_exists"
 
And a new default `pve_reboot_on_kernel_update_delay` with defaults to 60. In my environment I've set it to 300.

Do you think, `throttle` is in general a good idea here? Or should we double the task once with `pve_cluster_enabled=true' and one with false?

**Comment by trickert76** [comment]
see #146

**Comment by lae** [comment]
wait I just realised after merging but

I think you could just put 'throttle: pve_cluster_enabled | bool | ternary(1, omit)` into the task instead of duplicating it...? either way, merged 146 so closing.

**Comment by trickert76** [comment]
Ah very good point. I‘ll change that next week.
