### ISSUE TITLE
Move tests off Travis CI to another CI deployment

### ISSUE THREAD

**Issue by lae** [lae/ansible-role-proxmox#166]
Leaving this as a placeholder for myself, maybe I'll get around to it eventually. Last I checked Travis CI limitations aren't really favorable to me, so I'd like to move off (especially now that .org has been shutdown). Although, it's possible I could use my student status to get extra quota or something on travis-ci.com—I should look into that.

Ideally though I will have stood up a Drone CI (or at least that's what I've been leaning towards for a few years) deployment in my homelab that we can use for testing this role, and once that happens I can write a drone.yml definition + update the tests directory as necessary to run tests against PRs as well as regularly against the main branches (to find any upstream breakage).

**Comment by thystips** [comment]
I use only Github Actions (on self hosted) at work and I have same requirements and need to prepare something for testing roles and collections.
Actually I only have `ansible-lint`, `reuse` check (license), changelog generation and release creation for our collections. But in the medium to long term I have to add automatic tests.
After that I could propose you a solution if you want to use Github Actions if you want.

**Comment by lae** [comment]
That would definitely help as a reference! I have some ideas/wants since I started using Actions recently so ideally I'll implement this myself, but existing examples would very much be appreciated.

**Comment by thystips** [comment]
For now this collection is messy but Github Actions for ansible-lint working well : [Github Actions test file](https://github.com/weytop/ansible-infrastructure-collection/blob/main/.github/workflows/test.yml)

I use pipenv to respect our internal guideline but it's also working with a simple `apt install ansible-lint` or equivalent.

**Comment by lae** [comment]
The real Actions workflow replacement with functional testing is now introduced by #337.
