### ISSUE TITLE
VFIO support

### ISSUE THREAD

**Issue by lae** [lae/ansible-role-proxmox#167]
So a lot of people have started using PVE for their VFIO setups, it looks like, and so have I recently. We can probably simplify the setup for it in this role like we do for watchdog and ZFS. Setup instructions can be found on the wiki (sections 1-3 is all that's needed, the others are only relevant to the creation of VMs):

https://pve.proxmox.com/wiki/Pci_passthrough

This is probably a good chance for someone new to familiarize themselves with this role's codebase, so let me know if anyone's interested and I'll help guide you through it.

**Comment by deloa6133** [comment]
Hello I would be interested in helping out, I already have a decent working model of this built from v1.7.1
