### ISSUE TITLE
Failed to convert the throttle value to an integer

### ISSUE THREAD

**Issue by skipperTux** [lae/ansible-role-proxmox#177]
Role version: latest develop (34526de)
Ansible version: [Ansible 4.7.0 (Ansible-core version 2.11.6)](https://github.com/ansible-community/ansible-build-data/blob/main/4/CHANGELOG-v4.rst#release-summary)
pve_cluster_enabled: false

```
ERROR! Failed to convert the throttle value to an integer.

The error appears to be in '/home/cloudbox/.ansible/roles/lae.proxmox/tasks/kernel_updates.yml': line 8, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: "Reboot for kernel update"
  ^ here
```

See #145 , looks like the omit syntax does not work with the [throttle keyword](https://docs.ansible.com/ansible/latest/user_guide/playbooks_strategies.html#restricting-execution-with-throttle).

**Comment by lae** [comment]
This was fixed in https://github.com/lae/ansible-role-proxmox/pull/173 but hasn't been merged since I've yet to get someone to review it/test it. Do you think you could test that branch out (and if you're up for it, review it as well)?

**Comment by lae** [comment]
Never mind that last comment (removed it).

I knew I fixed this but I guess I had not merged that branch. Will merge it now. https://github.com/lae/ansible-role-proxmox/commit/c97f73a2f327a2c916f6f1702ef1c5fcbe80f519
