### ISSUE TITLE
ansible galaxy install missing file for v1.6.9

### ISSUE THREAD

**Issue by jfelten** [lae/ansible-role-proxmox#180]
I am getting the following error from my playbook configuring a proxmox 7 cluster:
```
fatal: [xxx.xxx.com]: FAILED! => {"ansible_facts": {}, "ansible_included_var_files": [], "changed": false, "message": "Could not find or access 'debian-bullseye.yml'\
```

I believe this to be caused by the ansible-galaxy install the contains the incorrect files:
```
ansible-galaxy install lae.proxmox
Starting galaxy role install process
- downloading role 'proxmox', owned by lae
- downloading role from https://github.com/lae/ansible-role-proxmox/archive/v1.6.9.tar.gz
- extracting lae.proxmox to ~/.ansible/roles/lae.proxmox
- lae.proxmox (v1.6.9) was installed successfully

 ls ~/.ansible/roles/lae.proxmox/vars/
debian-buster.yml  debian-stretch.yml  main.yml

```
debian-bullseye.yml is missing, but is present on github. Something is wrong with the download build artifact.

**Comment by lae** [comment]
No, there's nothing wrong with the artifact. 1.6.9 does *not* have support for Debian Bullseye/PVE 7:

https://github.com/lae/ansible-role-proxmox/tree/v1.6.9/vars

I was planning to make a new minor version release (1.6→1.7) after I could get someone to review a PR fixing a clustering bug but I guess I haven't been able to get someone to, yet....

For PVE 7 you'll want to install the develop branch directly via ansible-galaxy until that release happens.

**Comment by jfelten** [comment]
got it. thanks!

**Comment by jfelten** [comment]
Is this related to the issue you are trying to fix?
```
TASK [ansible-role-proxmox : Ensure that facts are present for all cluster hosts] ****************************************************************************************************
fatal: xxx.xxx.com]: FAILED! => {"msg": "'dict object' has no attribute 'proxmox'"}
```
If so I can test it for you, since I am trying to configure a cluster.

**Comment by lae** [comment]
No. That looks like it would be an issue with your role variables (specifically `pve_group`) and/or inventory. Since that's the default, I'm guessing you didn't make a `proxmox` group in your inventory?

Anyway, the PR I'm talking about is https://github.com/lae/ansible-role-proxmox/pull/173 and it's been tested out a bit already; a review to make sure nothing is missing in the proposed changes is what I would want. I'll try to review it myself later since quite some time has already passed, though.

**Comment by jfelten** [comment]
thank you - it is working.
