### ISSUE TITLE
The mounted cephfs result in the same one

### ISSUE THREAD

**Issue by timtorChen** [lae/ansible-role-proxmox#193]
It seems we lack a filesystem option here.
https://github.com/lae/ansible-role-proxmox/blob/174b6da65e5aebe6052aabe23eb20130fa9d6427/tasks/ceph.yml#L244

The filesystem specify option is related to ceph version. In ceph 14 it use `mds_namespace=<fs-name>`, but in ceph 15, and 16 it is changed to `fs=<fs-name>`. If there is no specifed option ceph will mount the default one.

Maybe create a python script like `library/pve_ceph_version.py`, fetching the ceph version facts, and the add the corresponded option? If this is a good idea, I can try create a PR.

By the way, thanks for this ansible role really helps me buld a homelab.

**Comment by lae** [comment]
Does this actually need a python script?

PVE 7 shipped with Ceph Pacific (16), and installing current versions of PVE 6 bring in Ceph Octopus (15), so I would think it should be fine to just use `fs=<fs-name>` going forward. Or are you currently on an older PVE 6 installation with Ceph 14?

**Comment by timtorChen** [comment]
I'm using Proxmox 7 with ceph 16. Well, as the EOL is on July 2022, I think simplly add `fs` is the nice.

**Comment by lae** [comment]
upstream documentation regarding this https://docs.ceph.com/en/pacific/cephfs/mount-using-kernel-driver/
