### ISSUE TITLE
Deployment doesn't work on Debian 11 VMs created from the official cloud init images

### ISSUE THREAD

**Issue by pgagarinov** [lae/ansible-role-proxmox#210]
The reason is Debian 11 cloud init image from https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-arm64.raw  uses "source-directory" inside `/etc/network/interfaces` to include `/etc/network/interfaces.d` while ifupdown2 (which is a default option for PVE starting with version 7.0) doesn't understand 'source-directory' and expects 'source' instead - see https://github.com/CumulusNetworks/ifupdown2/issues/191

**Comment by lae** [comment]
This role itself doesn't manage network interfaces. Any network configuration and quirks are meant to be managed outside of this role, hence why they are separate tasks in the examples provided in the documentation.

**Comment by lae** [comment]
Closing - if you think there still needs to be something done please reopen.
