### ISSUE TITLE
[documentation] Add `ansible.posix` and `community.general` to the requirements

### ISSUE THREAD

**Issue by b-** [lae/ansible-role-proxmox#222]
Hey there,

I think this is a new change (for some definition of "new"), but when I installed Ansible by way of `python3 -m pip install ansible` in a venv it did not automatically install the `ansible.posix` or `community.general` collections. I wonder if they're moving to something closer to ansible-core for all new installs, or something? Or maybe they moved some modules out from `builtin` or something? I'm not sure, I'm pretty new to Ansible.

Your role as well as Jeff Geerling's NTP role require either or both of those collections. I didn't dig too deeply into what exactly, so I don't know what the best way to do this would be.

Would it make any sense to add your own `requirements.yaml` (or even maybe `requirements.example.yaml`) to the repository?

**Comment by lae** [comment]
That seems kind of weird. I haven't personally kept myself up to date with how collections are being handled in the ecosystem, but on a quick cursory check, I grabbed the tarballs from PyPi:

```
[lae@sumire tmp]$ tar tvf ansible-7.5.0.tar.gz | grep -c ansible/posix
307
[lae@sumire tmp]$ tar tvf ansible-8.0.0a2.tar.gz | grep -c ansible/posix
307
[lae@sumire tmp]$ tar tvf ansible-8.0.0a2.tar.gz | grep -c community/general
3571
[lae@sumire tmp]$ tar tvf ansible-7.5.0.tar.gz | grep -c community/general
3571
```

Seems like the collections are in the Ansible package?

**Comment by b-** [comment]
I think that's my mistake, I thought I was in my venv but I was not, and somehow I had a globally-installed Ansible that was just plain incorrect. Forgive me!
