### ISSUE TITLE
Add compatiblity with debian 12

### ISSUE THREAD

**Issue by lexxxel** [lae/ansible-role-proxmox#226]
Currently, this role does not support debian 12 and proxmox 8.x.

I saw that at least `files/proxmox-ve-release-8.x.asc` as well as `vars/debian-bookworm.yml` is missing.
Possibly, step `Trust Proxmox' packaging key` has to be rewritten, too, because `apt_key` is deprecated

**Comment by Andre15711** [comment]
Yes, PVE 8.x support would be great.

**Comment by chief-wrench** [comment]
I would greatly appreciate when this got merged.

**Comment by willifehler** [comment]
Any update here?

**Comment by lae** [comment]
貼るべきではございませんけど人生初めてそういう主張を体験しまして、つい…　大変失礼いたしました。
![image](https://github.com/lae/ansible-role-proxmox/assets/1318013/1ba30d06-dd98-4a5d-9f17-7685b27d3a43)

yes.
