### ISSUE TITLE
Looking for sponsor or contract/FT work

### ISSUE THREAD

**Issue by lae** [lae/ansible-role-proxmox#234]
I'll keep this short (I tried...).

Without going into too much detail in public, I've had significant trouble restarting my career after obtaining a degree in CS. Things have generally been not so great since the start of the pandemic in 2020, unfortunately (I've previously indicated something like this in another project, https://github.com/lae/ansible-role-netbox/issues/132). I've hesitated asking for help on GitHub for over a year now, but I feel like anyone reading this would be in a better position to point me to relevant work.

Some things I'm looking for in a role are:

- focuses on automation/IaC, i.e. using terraform and ansible
- includes software dev in some fashion
- lets me use this role (...pun not intended, I swear) on a professional basis again, so I can better maintain it.
- is ideally flex time and remote, but on-site/relocation may be negotiable (especially if visiting facilities is a requirement)

This is a call for roles based in the States (tax residence), but historically I have been looking for work and visa sponsorship in Japan (Tokyo or Sapporo), so I will prioritize roles there (esp. if they're 正社員 and not 業務委託) if anyone has leads. Taiwan could also work (but I do not know Mandarin).

CV here: https://github.com/lae/resume
_edit 2.24:_ This is no longer publicly kept up to date, but I have been contracted as a full stack engineer for a year now. This situation can be discussed in a confidential interview.
_edit 3.1_: This has been in the process of being rewritten since a few days ago, which will be public later in some form (old roles at least).

If you have leads (or maybe even want to work with me yourself...) please reach out to `arbeiter (＠) lae.is`. Will close or remove this once I have...something I'm happy with, I guess. Thanks for your time.

**Comment by gilou** [comment]
for what it's worth, as I don't have the opportunity to hire you directly, I at least shared the issue on Mastodon @ https://mastodon.social/@Gilou/111929065169800272

**Comment by lae** [comment]
Closing because for the time being I have a contract and am no longer strapped for money/can finally pay rent, but I am still open to further contract work and ideally a full time visa-supported role in Tokyo/Sapporo/Taiwan or elsewhere in an APAC country.
