### ISSUE TITLE
Feature Proposal : Transform Ansible Role into a Ansible Collection

### ISSUE THREAD

**Issue by thystips** [lae/ansible-role-proxmox#260]
It would be useful to transform the current Ansible role into a collection that allows users to use specific libraries or functions without needing to run the entire Proxmox role.

For example:

- Managing storage with a custom role dedicated to storage arrays.
- Handling user management independently.
- Managing `Metric Server` with a role dedicated for monitoring (mentioned in  #259)
- Resolv #186
- Make #36 easier to hack

This transformation would allow for splitting Proxmox installation, storage management, SSH configuration, etc., into separate roles within the collection, providing more flexibility and modularity.

Thanks for considering this!

**Comment by lae** [comment]
This is already something I've thought about, but it is outside of scope. A collection is not backwards compatible and would have to be a separate project, which is not one that I would really have the motivation to maintain/create at this time.
