### ISSUE TITLE
Issue: Align role name and variables with ansible-lint standards

### ISSUE THREAD

**Issue by thystips** [lae/ansible-role-proxmox#261]
I've submitted a pull request to fix most of the issues flagged by ansible-lint #255. However, one of the remaining issues is that all variables should use the role's name as a prefix.

Currently, the variables are prefixed with pve, while the role is named proxmox. To comply with ansible-lint standards, we have two possible solutions:

1. Rename the variables to use the proxmox prefix.
2. Rename the role from proxmox to pve to match the existing variable prefixes.

Either solution would bring the role in line with ansible-lint recommendations.

Thank you for considering this adjustment!

**Comment by lae** [comment]
Not something I agree with. Linters are only meant as a guideline. Unless there is a technical reason that prompts needing this change, this lint rule seems fine to ignore and would only cause headaches for the many people already using this role if we were to do either of these.

**Comment by lae** [comment]
I just noticed/recalled that it was a conscious decision to rename the variables, at least: https://github.com/lae/ansible-role-proxmox/commit/8a48f7aa36f810651e85a8c934b18d19a9afd0a2
I guess I *could've* also renamed the role in conjunction, but alas I did not...
