### ISSUE TITLE
ADD Solution to README: APT becomes unresponsive on the "proxmox-ve" package installation

### ISSUE THREAD

**Issue by iPaulTech** [lae/ansible-role-proxmox#279]
I had problems with the installation of the `proxmox-ve` package using the APT task.

After I added the following code section to the `ansible.cfg` file, the role ran successfully several times.
```
[ssh_connection]
ssh_args = -o ServerAliveInterval=20
```

I would therefore recommend including this section in the README, as I had to debug for about 2 weeks before I could finally narrow down the problem.

**Comment by lae** [comment]
There's got to be something peculiar about your environment (in comparison to the several other admins that use this role) that necessitates this. Maybe a non-standard `/etc/ssh/sshd_config` on the hosts? Either way, it wouldn't hurt to suggest setting this in the docs.

I would add a *Troubleshooting* section in the README between the *Non-default scenarios* and *Developer Notes*, and use similar formatting to the *Non-default scenarios* section for this. Do you think you could write a snippet/open a PR for this?

**Comment by iPaulTech** [comment]
> Maybe a non-standard /etc/ssh/sshd_config on the hosts?

Good point! After comparision: No, the SSHD config is equal to debian default.
I've tested the deployment even with a fresh debian installation.
md5sum of my original sshd_config: e6fd6e8e29210c5678181f33177d5433

> Do you think you could write a snippet/open a PR for this?
No Problem, merge it :+1: 
https://github.com/lae/ansible-role-proxmox/pull/281
