### ISSUE TITLE
Support bare minimum storage config management

### ISSUE THREAD

**Issue by lae** [lae/ansible-role-proxmox#35]
Would be a nice-to-have for a lot of people, I think.

**Comment by bozho** [comment]
Ah, sorry. Not sure how I missed that one :)

Do you have any plans or ideas already? I wouldn't mind helping out.

**Comment by lae** [comment]
Any ideas I've had I've forgotten by now, lol. I'll need to review the role again and experiment, but I believe it should be similar to how the other Proxmox configuration modules (see `library/proxmox_acl.py` for example) are implemented. You can also look at some closed PRs to get an idea of what all you should add (tests, docs etc).

Look at the PVE API documentation, specifically the /storage API endpoint: https://pve.proxmox.com/pve-docs/api-viewer/index.html

Think that's enough to get started? I can assign this to you if you want.

**Comment by lae** [comment]
@bozho Are you still interested in tackling this?

**Comment by Fbrachere** [comment]
Hi,
I'm writing this ansible storage module and i'm facing to a problem:
Once storage is created, we can not change some parameters.
For example for a "rbd" storage type, pool and username can not be changed.
I don't know what is the best strategy:
- when you play role, if storage ID exists, try to change the parameters and throw an error if they can not be changed.
- delete the storage and recreate it with updated parameters.
An ideas ?

**Comment by lae** [comment]
I think deleting the storage entry might not be possible if the entry is in use by VMs?

Since Proxmox itself doesn't allow changing those parameters from the UI in the first place, I think we should throw an error if someone tries to change it in Ansible.

**Comment by Fbrachere** [comment]
> I think deleting the storage entry might not be possible if the entry is in use by VMs?

Yes, it's possible even with running VMs, I tried it. But it can be dangerous, if delete is OK and there is a problem with storage creation, you're in trouble.

**Comment by lae** [comment]
Another option could just be to template out /etc/pve/storage.cfg directly, but we can't use the `template` module as-is (because it breaks on the FUSE filesystem). I would just go with the simplest way and just not let the user change "immutable" params on an already existing storage ID (so yeah, throw an error).

**Comment by lae** [comment]
Resolved in the PR referenced above. Thanks a lot, @Fbrachere!

@bozho Feel free to test this (`develop` branch still) and let me know if you run into any issues.

**Comment by bozho** [comment]
Hi, I probably won't have the time this year, I'm quite swamped. But I'll be happy to do it in January :)

**Comment by lae** [comment]
No worries!
