### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by trickert76** [lae/ansible-role-proxmox#59]
I don't want to install Python2 on my new hosts, the support ends this year. So I tried your role with a Python3 only host and got the following error:

```
TASK [lae.proxmox : Check for kernel update] *****************************************************************************************************************************
fatal: [ac-sh0001]: FAILED! => 
{
  "changed": false, 
...
    File \"/tmp/ansible_collect_kernel_info_payload_96ul2c8o/__main__.py\", line 71, in <module>\r\n
    File \"/tmp/ansible_collect_kernel_info_payload_96ul2c8o/__main__.py\", line 67, in main\r\n
        TypeError: a bytes-like object is required, not 'str'\r\n",
  "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
  "rc": 1
}
```
The error is in the library/collect_kernel_info.py line 67, where two strings are splittet and partly compared. I'm not a Python developer (yet), but the Strings should be converted. But I'm not sure, if this is a good idea. If you give me an idea, what to do, I would create a fix.

**Comment by trickert76** [comment]
There is another situation in line 61, when I skip the kernel_reboot property.

**Comment by lae** [comment]
Debian 9 is still default Py2 afaik - but yeah the role should still work with Py3 hosts.

Adding a `.decode()` to convert the bytes objects from the `subprocess` calls into unicode objects should suffice, I think, e.g. on line 54.

**Comment by lae** [comment]
https://docs.ansible.com/ansible/2.5/dev_guide/developing_python_3.html#porting-controller-code-to-python-3

Actually, I guess we should use `to_text()` from Ansible here instead.

**Comment by lae** [comment]
Almost forgot to mention. While I believe this has been fixed (and current tests appear to have passed) - PVE still depends on Python 2 on the host as far as I can tell so I haven't permanently moved tests to use Python 3 (mainly to avoid the extra time it adds to tests).

**Comment by trickert76** [comment]
Yes, I think, we should create an issue for Python3 support. I need to switch always explicit the ansible_interpreter when running this role. Next time I add a new host to my cluster, I'll remove that switch and have a look at what happens (or not). I'll open then new issues.

**Comment by lae** [comment]
The `Vagrantfile` I added yesterday sets the ansible interpreter to py3:

https://github.com/lae/ansible-role-proxmox/blob/develop/tests/vagrant/group_vars/all

It worked fine (after the py3 fixes I made) - my last comment just means I won't be including regular automated tests for it until PVE 7 or something, probably. It's really unlikely anything will break for py3 anyway since the modules don't really get modified very often.
