### ISSUE TITLE
OSD creation isn't fully idempotent

### ISSUE THREAD

**Issue by lae** [lae/ansible-role-proxmox#73]
Splitting off issue #72.

>I finished with this issue and testing the other #69 (took some time to prepare my bare metal cluster that I am going to install). I have some problems regarding idempodent creation of osd. The role stops if an osd is already in use.
>
>@lae  Should we check, if a defined OSD is already in use and move on with the other tasks?
>
>Example:
>I had some timeout during OSD creation and it was necessary to replay the playbook. The OSD's were created properly but the execution stops after OSD creation. Role does not create pools and storages at this stage.

_Originally posted by @mholasek in https://github.com/lae/ansible-role-proxmox/issues/72#issuecomment-539083013_

>yes - I'm unfortunately not able to test idempotency of that part myself (no longer working at fireeye/don't have access to a lot of physical hardware anymore) and CI can't either. All tasks should be made idempotent.
>
>I'm not sure if you can just use a `creates` argument on the OSD creation step (because iirc OSD creation picks a random number for the folder name) but maybe you could add another task before the creation step to check if there is an existing OSD associated with the selected drive, and then skip OSD creation/configuration tasks based on the result?

_Originally posted by @lae in https://github.com/lae/ansible-role-proxmox/issues/72#issuecomment-539086108_

>@lae I am not sure why the current osd creation is done via "creates:" argument by checking for a /dev/sd?1. I'll do my tests with proxmox v6.0 and nautilus and it does not create any partition.  Maybe this is correct under luminous, but I have no chance to test this.
>
>Thats why I tried another approach by checking if there is already any ceph lvm volume via ```ceph-volume lvm list```command. But I am not sure if this can be used for luminous as well (but I'll guess).
>
>What do you think, should we go for this? If OK, I'll do some additional testing, enhance the readme within the next days and create a pull request after that. Maybe we mention, that ceph task is still beta and only tested with proxmox v6.0? You can take a look at the fork (feature branch): https://github.com/mholasek/ansible-role-proxmox/tree/feature/ceph-replication-network.

_Originally posted by @mholasek in https://github.com/lae/ansible-role-proxmox/issues/72#issuecomment-539579164_

>@mholasek What's some example JSON output from that command once you get a successful OSD provisioned with `pveceph`? ([docs](https://docs.ceph.com/docs/master/ceph-volume/lvm/list/) show that you can use `--format=json`) Just to confirm, the `lvm list` command doesn't have anything to do with Linux LVM, right? (In other words, this command should be appropriate for checking provisioned OSDs in all deployment scenarios with pveceph?) If that's the case, we could possibly create a small Ansible module for OSD creation without needing to write any parsing code.
>
>So I had forgotten earlier, but I believe `{device}1` was selected on the basis that the `pveceph osd create` command creates a partition on the device, and that was picked instead of something like `/var/lib/ceph/osd-5` (which is what I was referring to in my previous comment) to keep the OSD creation step idempotent. (For mutual reference, you're referring to [this line](https://github.com/lae/ansible-role-proxmox/blob/v1.6.1/tasks/ceph.yml#L66), right? So it's not necessarily `/dev/sd?1`, unless you're finding that somewhere else?) The `pveceph` tool expects the devices passed to be one the patterns listed in [this comment](https://github.com/lae/ansible-role-proxmox/pull/52#issuecomment-483853661), at least in PVE5. Are you trying with something different? (maybe you could check if that code is any different in PVE6?)
>
>Also, I did add a note to the README in the Ceph PR I mentioned earlier stating that *PVE Ceph management with this role is experimental*, so I think we're fine there.

_Originally posted by @lae in https://github.com/lae/ansible-role-proxmox/issues/72#issuecomment-539608972_

**Comment by lae** [comment]
@mholasek What's some example JSON output from that command once you get a successful OSD provisioned with `pveceph`? ([docs](https://docs.ceph.com/docs/master/ceph-volume/lvm/list/) show that you can use `--format=json`) Just to confirm, the `lvm list` command doesn't have anything to do with Linux LVM, right? (In other words, this command should be appropriate for checking provisioned OSDs in all deployment scenarios with pveceph?) If that's the case, we could possibly create a small Ansible module for OSD creation without needing to write any parsing code.

So I had forgotten earlier, but I believe `{device}1` was selected on the basis that the `pveceph osd create` command creates a partition on the device, and that was picked instead of something like `/var/lib/ceph/osd-5` (which is what I was referring to in my previous comment) to keep the OSD creation step idempotent. (For mutual reference, you're referring to [this line](https://github.com/lae/ansible-role-proxmox/blob/v1.6.1/tasks/ceph.yml#L66), right? So it's not necessarily `/dev/sd?1`, unless you're finding that somewhere else?) The `pveceph` tool expects the devices passed to be one the patterns listed in [this comment](https://github.com/lae/ansible-role-proxmox/pull/52#issuecomment-483853661), at least in PVE5. Are you trying with something different? (maybe you could check if that code is any different in PVE6?)

Also, I did add a note to the README in the Ceph PR I mentioned earlier stating that *PVE Ceph management with this role is experimental*, so I think we're fine there.

**Comment by lae** [comment]
It looks like the `ceph-ansible` repository has an existing Ansible module that we could probably leverage.  https://github.com/ceph/ceph-ansible/blob/master/library/ceph_volume.py

**Comment by mholasek** [comment]
Great. The ceph_volume ansible module looks promising. I‘ll try to do it with that.

**Comment by zenntrix** [comment]
So is the current advice to not configure ceph using this role and instead use ceph-ansible? Is this an interim suggestion or something that will stick and as such should the ceph configuration be removed from this role?

**Comment by lae** [comment]
That is not the advice provided at all for end users. My previous comment was meant for providing some module source code from that role (read: not the entire role) that would assist in updating the role towards more correct idempotency.

Ceph configuration using PVE tools in this role works for many people as far as I know. There's no reason to remove it.

**Comment by zenntrix** [comment]
Thank you for the clarification, i will continue my endeavours to get this working using the configuration provided then. I am having issues with provisioning OSD's via this role. Once i get it working i will attempt to improve the documentation for further users.

**Comment by lae** [comment]
@zenntrix feel free to join the Discord server mentioned under Support in the README, or PM me on IRC (lae on Freenode/Mozilla).

**Comment by lae** [comment]
@zenntrix any luck?

This issue should be resolved by #81 - but I need testers before merging it. Think you could try it out?

**Comment by zenntrix** [comment]
Just trying it now, will report back.

**Comment by zenntrix** [comment]
@lae, the problem i am seeing when installing on a fresh bare-metal is 

`235:
TASK [ansible-role-proxmox : Create Ceph OSDs] *********************************
 236:
failed: [proxmox-test.corp.####.com] (item={u'device': u'/dev/sdb'}) => {"ansible_loop_var": "item", "changed": true, "cmd": ["pveceph", "osd", "create", "/dev/sdb"], "delta": "0:00:01.461373", "end": "2019-11-18 20:04:43.436298", "item": {"device": "/dev/sdb"}, "msg": "non-zero return code", "rc": 25, "start": "2019-11-18 20:04:41.974925", "stderr": "device '/dev/sdb' is already in use", "stderr_lines": ["device '/dev/sdb' is already in use"], "stdout": "", "stdout_lines": []}
 237:
failed: [proxmox-test.corp.####.com] (item={u'device': u'/dev/sdc'}) => {"ansible_loop_var": "item", "changed": true, "cmd": ["pveceph", "osd", "create", "/dev/sdc"], "delta": "0:00:00.968795", "end": "2019-11-18 20:04:44.735755", "item": {"device": "/dev/sdc"}, "msg": "non-zero return code", "rc": 25, "start": "2019-11-18 20:04:43.766960", "stderr": "device '/dev/sdc' is already in use", "stderr_lines": ["device '/dev/sdc' is already in use"], "stdout": "", "stdout_lines": []}`

I have the following ansible parameters set:

**pve_ceph_crush_rules:** - name: hdd
**pve_ceph_enabled:** true
**pve_ceph_mds_group:** all
**pve_ceph_pools:** 
  - name: vm-storage
    pgs: 128
    application: rbd
    storage: true
  - name: k8-storage
    pgs: 64
    application: rbd
**pve_storages:**
- name: vm-storage
  type: rbd
  content:
  - images
  - rootdir
  pool: vm-storage
  username: admin
  monhost:
  - proxmox-test.corp.####.com
**pve_ceph_osds:**
- device: "/dev/sdb"
- device: "/dev/sdc"


Any ideas what i am missing?

**Comment by lae** [comment]
Hm, that doesn't seem to be related to this issue if you're getting that on your first run. I'm moving this to a separate issue.

**Comment by lae** [comment]
Fixed by #81
