### ISSUE TITLE
Creation of users in pve realm with password

### ISSUE THREAD

**Issue by pvanhemmen** [lae/ansible-role-proxmox#80]
Hey there,

I'm trying to create an api user in the PVE realm with a password like this:

```
pve_users:
  - name: api@pve
    password: "MyPassword123"
    groups:
      - api_users
```

While the  user itself gets created correctly, the corresponding password is not stored on the server, thus the user is not able to login. According to the [documentation](https://pve.proxmox.com/wiki/User_Management#pveum_authentication_realms) passwords in the pve realm should be encrypted and written to `/etc/pve/priv/shadow.cfg`. This file does not exist upon creation of the user through this role.

I'm able to set the password for the user from within the web admin manually, upon which the file is created and I'm able to login with the user. Maybe I'm missing something here?

**ansible 2.8.5** on **macOS 10.15.1**
**Debian 10.1**
**Proxmox 6.0-9**

Thanx!

**Comment by lae** [comment]
Hm, the role uses the Proxmox API to create/modify users. I'll see if I can reproduce this.

**Comment by pvanhemmen** [comment]
If I can help, please let me know!

**Comment by lae** [comment]
Checked the API docs and I *think* the `password` field was removed on the creation endpoint:

![image](https://user-images.githubusercontent.com/1318013/68072682-76403180-fd45-11e9-822d-3e9f77bb1525.png)

Looks like there's a separate endpoint for configuring the password, so `library/proxmox_user.py` will need to be modified to work with it.
