### ISSUE TITLE
File /usr/share/pve-manager/ext6/pvemanagerlib.js changed location in PVE 4.5

### ISSUE THREAD

**Issue by ikus060** [lae/ansible-role-proxmox#9]
In recent version of  PVE 4.5, the file `/usr/share/pve-manager/ext6/pvemanagerlib.js` is moved to `/usr/share/pve-manager/js/pvemanagerlib.js`.

Take note, the patch is still working.

**Comment by lae** [comment]
Fixed in https://github.com/lae/ansible-role-proxmox/releases/tag/v1.1.0
