### ISSUE TITLE
interfaces template and resolvconf

### ISSUE THREAD

**Issue by jfpanisset** [lae/ansible-role-proxmox#92]
In the section of README.md which discusses the interfaces-{{ pve_group }}.j2 template, the sample code demonstrates setting the DNS servers inside the `iface` section:

```
    dns-nameservers 10.2.2.4 10.3.2.4
    dns-search local
```

But based on [Defining the DNS Servers](https://wiki.debian.org/NetworkConfiguration#Defining_the_.28DNS.29_Nameservers), it appears that this is only the case if you have installed the `resolvconf` package: on a fresh install of Proxmox this is not present, and the original installer will have created a static `/etc/resolv.conf` file.

So perhaps this should be noted in the documentation, and/or explicit code to configure `/etc/resolv.conf` could be added, similarly to the support for configuring NTP?

**Comment by lae** [comment]
That section is really just an example playbook (configuring interfaces is outside the scope of the role itself) and isn't meant to be super comprehensive because everyone's environments are different.

Thoughts on just removing those lines from the interfaces example altogether, to prevent possible confusion from those extraneous options (as far as I can tell)?

**Comment by jfpanisset** [comment]
I've submittted PR #94 to suggest possible wording to discuss this issue. If I remember well the default Proxmox installer only lets you specify a single DNS server (I could be wrong), and I'm guessing that most cluster configurations would want at least 2.

**Comment by trickert76** [comment]
I would remove that two lines from the example and thats it. Every environment is different. In my case I would not install resolvconf and use the /etc/resolv.conf and I have templates in a different role for setup the DNS etc.
